"""D5-UI: one-click summary button page (no build step).

GET /ui -> single HTML file: session + token fields, a "Catch me up" button
that shows the recap text, plus auto-poll of the rolling summary that flashes
a NEW badge whenever fresh text lands.
"""
from __future__ import annotations

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse

router = APIRouter()

PAGE = """<!doctype html><html><head><meta charset="utf-8">
<title>Stream Summary</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;700&display=swap" rel="stylesheet">
<style>
body{font-family:"Geist",system-ui,-apple-system,sans-serif;background:#101216;color:#f2f3f5;margin:0;padding:32px 16px;display:flex;justify-content:center;min-height:100vh}
.wrap{width:100%;max-width:520px}
.catchrow{margin-bottom:12px}
#btn{font-family:inherit;font-size:16px;font-weight:600;padding:10px 22px;border-radius:10px;border:0;background:#e8eaed;color:#111;cursor:pointer}
.new{display:inline-block;background:#2563eb;color:#fff;font-size:11px;font-weight:700;border-radius:4px;padding:2px 6px;margin-left:8px;vertical-align:middle;animation:blink 1s step-end infinite}
@keyframes blink{50%{opacity:0}}
.card{background:#22252c;border-radius:14px;padding:16px 20px;box-shadow:0 10px 32px rgba(0,0,0,.5)}
.head{display:flex;align-items:center;gap:10px}
.ttl{font-weight:700;font-size:17px;flex:1}
.xbtn{background:transparent;border:0;color:#c9ced6;font-size:18px;cursor:pointer;padding:4px}
#bodyTxt{white-space:pre-wrap;margin:14px 0 4px;font-size:15px;line-height:1.55}
.q{font-weight:700;margin:14px 0 10px;font-size:15px}
.pills{display:flex;gap:10px}
.pill{font-family:inherit;background:#3a3f47;color:#fff;border:0;border-radius:999px;padding:9px 24px;font-size:15px;cursor:pointer}
.pill:hover{background:#4b515a}
.pill.picked{background:#2563eb}
.pill:disabled{cursor:default}
.pill:disabled:not(.picked){opacity:.45}
.foot{color:#9aa0aa;font-size:12.5px;margin-top:14px}
#showbar{display:none;font-family:inherit;background:#22252c;color:#fff;border:0;border-radius:999px;padding:10px 22px;font-size:15px;cursor:pointer}
</style></head><body>
<div class="wrap">
<div class="catchrow"><button id="btn">Catch me up<span id="newTag" class="new" style="display:none">NEW!</span></button></div>
<div class="card" id="card">
<div class="head"><span>&#9776;</span><span class="ttl">Stream Summary</span><button class="xbtn" id="xbtn">&#10005;</button></div>
<div id="cardbody">
<div id="bodyTxt">Loading latest summary&hellip;</div>
<div class="q">Was this summary easy to understand at a glance?</div>
<div class="pills"><button class="pill" data-v="yes">Yes</button><button class="pill" data-v="no">No</button><button class="pill" data-v="not_sure">Not Sure</button></div>
<div class="foot">Generated by AI. May make mistakes.<span id="votenote"></span></div>
</div>
</div>
<button id="showbar">Show summary</button>
    <script>
const SID=1;
let TOK=sessionStorage.getItem("stream-summary-token")||"";
if(!TOK){TOK=window.prompt("API bearer token")||"";if(TOK)sessionStorage.setItem("stream-summary-token",TOK);}
const clean=t=>(t||"").replaceAll("**","");
let displayed="";
let rolling="";
let baseKey="";
let currentId=null,currentKind="rolling";
async function keyNow(){try{const r=await fetch(`/api/v1/sessions/${SID}/recap-status`,{headers:{Authorization:"Bearer "+TOK}});
const j=await r.json();return j.key||"";}catch(e){return "";}}
function resetVotes(){document.querySelectorAll(".pill").forEach(b=>{b.disabled=false;b.classList.remove("picked");});document.getElementById("votenote").textContent="";}
function setText(t,kind,id){displayed=clean(t||"");document.getElementById("bodyTxt").textContent=displayed||"No summary yet.";currentKind=kind;currentId=(id==null?null:id);resetVotes();}
async function loadRolling(){try{const r=await fetch(`/api/v1/sessions/${SID}/summary`,{headers:{Authorization:"Bearer "+TOK}});
const j=await r.json();rolling=j.text||"";setText(rolling,"rolling",(j.id==null?null:j.id));}catch(e){document.getElementById("bodyTxt").textContent="error: "+e;}}
async function catchUp(){const box=document.getElementById("bodyTxt");box.textContent="loading…";
try{const r=await fetch(`/api/v1/sessions/${SID}/recap`,{headers:{Authorization:"Bearer "+TOK}});
const j=await r.json();setText(j.text||JSON.stringify(j),"recap",(j.id==null?null:j.id));
try{const s=await fetch(`/api/v1/sessions/${SID}/summary`,{headers:{Authorization:"Bearer "+TOK}});
const sj=await s.json();if(sj.text)rolling=sj.text;}catch(e){}
document.getElementById("newTag").style.display="none";baseKey=await keyNow();}catch(e){box.textContent="error: "+e;}}
async function vote(v,btn){try{await fetch(`/api/v1/sessions/${SID}/feedback`,{method:"POST",headers:{Authorization:"Bearer "+TOK,"Content-Type":"application/json"},body:JSON.stringify({summary_id:currentId,kind:currentKind,vote:v})});document.querySelectorAll(".pill").forEach(b=>{b.disabled=true;});btn.classList.add("picked");document.getElementById("votenote").textContent=" Thanks — this tunes future recaps.";}catch(e){}}
document.querySelectorAll(".pill").forEach(b=>{b.onclick=()=>vote(b.dataset.v,b);});
document.getElementById("btn").onclick=catchUp;
document.getElementById("xbtn").onclick=()=>{document.getElementById("card").style.display="none";document.getElementById("showbar").style.display="inline-block";};
document.getElementById("showbar").onclick=()=>{document.getElementById("showbar").style.display="none";document.getElementById("card").style.display="block";};
async function checkNew(){try{const k=await keyNow();
if(k&&baseKey&&k!==baseKey)document.getElementById("newTag").style.display="inline";}catch(e){}
setTimeout(checkNew,5000);}
async function boot(){await loadRolling();baseKey=await keyNow();checkNew();}
boot();
    </script></div></body></html>"""


@router.get("/ui")
def ui(request: Request):
    sid_raw = request.query_params.get("session")
    try:
        sid = str(int(sid_raw)) if sid_raw else None
    except (TypeError, ValueError):
        sid = None
    if sid is None:
        from sqlalchemy import select as _s2

        from app.db import models as m
        db = request.app.state.db_factory()
        try:
            active = db.execute(
                _s2(m.Segment.session_id).order_by(m.Segment.id.desc()).limit(1)
            ).scalar()
            if active is None:
                active = db.execute(
                    _s2(m.Session.id).order_by(m.Session.id.desc()).limit(1)
                ).scalar() or 1
            sid = str(active)
        finally:
            db.close()
    return HTMLResponse(PAGE.replace("const SID=1", f"const SID={sid}", 1))
